[package]
name = "levana_perpswap_cosmos"
version = "0.1.0-beta.15"
authors = ["Levana Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw-storage-plus = { version = "2.0.0", default-features = false }
serde = "1.0.214"
serde_json = "1.0.132"
cosmwasm-std = { workspace = true, features = ["abort"] }
cosmwasm-schema = { workspace = true }
pyth-sdk-cw = { workspace = true }
schemars = "0.8.21"
anyhow = "1.0.93"
cw2 = "2.0.0"
cw-utils = "2.0.0"
serde-json-wasm = "0.5.2"
arbitrary = { version = "1.4.1", optional = true, default-features = false, features = ["derive"] }
thiserror = "1"
chrono = { version = "0.4.38", optional = true, default-features = false, features = ["std"]}
enum-iterator = "1.5"
once_cell = "1.20"

[features]
default = ["bridge"]
bridge = []
arbitrary = ["dep:arbitrary"]

[dev-dependencies]
fs_extra = "1.3.0"
quickcheck = "1"
