price-api = "https://price-api.levana.exchange/"
qa-wallet = "levana1ssnwszx2dutvlrpwwgefpfyswgrrm059qp2zr2"

[liquidity]
min-util-delta = -0.05
max-util-delta = 0.02
target-util-delta = -0.02
[liquidity.markets]
[liquidity.markets.ATOM_USD]
min = 10000
max = 10000000
[liquidity.markets.OSMO_USDC]
min = 100000
max = 100000000
[liquidity.markets.SEI_USD]
min = 100000
max = 100000000
[liquidity.markets.OSMO_USD]
min = 100000
max = 100000000
[liquidity.markets.ETH_BTC]
min = 1000
max = 1000000
[liquidity.markets.ETH_USD]
min = 1000
max = 1000000
[liquidity.markets.axlETH_USD]
min = 1000
max = 1000000
[liquidity.markets.BTC_USD]
min = 100
max = 10000
[liquidity.markets.nBTC_USD]
min = 100
max = 10000
[liquidity.markets.ryETH_USD]
min = 1000
max = 1000000

[utilization]
min-util-delta = -0.1
max-util-delta = -0.05

[trader]
max-util-delta = 0.05
min-borrow-fee = 0.1
max-borrow-fee = 0.2

[initial-prices]
[initial-prices.ATOM_USD]
price = 7
price_usd = 7
[initial-prices.stATOM_USD]
price = 8
price_usd = 8
[initial-prices.ETH_BTC]
price = 0.5
price_usd = 28000
[initial-prices.OSMO_USDC]
price = 0.3
price_usd = 1
[initial-prices.BTC_USD]
price = 28000
price_usd = 28000

[deployments]
[deployments.beta]
wallet-manager-address = "osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k"
price = true
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ATOM_USD", "BTC_USD"]
[deployments.dev]
wallet-manager-address = "osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel"
dev-settings = true
price = true
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ATOM_USD", "BTC_USD"]
[deployments.ci]
wallet-manager-address = "osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv"
dev-settings = true
price = true
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["nBTC_USD", "ATOM_USD", "OSMO_USDC", "ETH_BTC", "BTC_USD", "axlETH_USD", "BTC_INJ"]
[deployments.debug]
wallet-manager-address = "levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9"
dev-settings = true
price = true
crank = 4
liquidity = false
utilization = false
balance = false
traders = 0
default-market-ids = ["BTC_USD", "ETH_USD"]
[deployments.qa]
wallet-manager-address = "levana1ep4uavfsyw5dp7ymtkpvj8qm4mc8ellph9408d"
dev-settings = true
price = false
crank = 4
ignore-stale = true
default-market-ids = ["ATOM_USD", "OSMO_USDC", "ETH_BTC", "BTC_USD"]
qa-price-updates = true

[overrides]
[overrides.seibeta]
wallet-manager-address = "osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k"
price = true
ultra-crank = 0
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ETH_USD", "BTC_USD"]
min-gas = 1000
min-gas-in-faucet = 2000000
min-gas-in-gas-wallet = 1000000
[overrides.seibeta.watcher]
retries = 10
[overrides.seidev]
wallet-manager-address = "osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel"
dev-settings = true
price = true
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ATOM_USD", "BTC_USD"]
min-gas = 1000
min-gas-in-faucet = 2000000
min-gas-in-gas-wallet = 1000000
[overrides.seidebug]
wallet-manager-address = "levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9"
dev-settings = true
price = true
crank = 4
liquidity = false
utilization = false
balance = false
traders = 0
default-market-ids = ["BTC_USD", "ETH_USD"]
min-gas = 1000
min-gas-in-faucet = 2000000
min-gas-in-gas-wallet = 1000000
[overrides.seici]
wallet-manager-address = "osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv"
dev-settings = true
price = true
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ATOM_USD", "OSMO_USDC", "ETH_BTC", "BTC_USD"]
min-gas = 1000
min-gas-in-faucet = 2000000
min-gas-in-gas-wallet = 1000000
[overrides.injbeta]
wallet-manager-address = "osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k"
price = true
ultra-crank = 0
crank = 4
liquidity = true
utilization = true
balance = true
traders = 0
default-market-ids = ["ETH_USD"]
