price-api: "https://price-api.levana.exchange/"
qa-wallet: levana1ssnwszx2dutvlrpwwgefpfyswgrrm059qp2zr2
liquidity:
  markets:
    ATOM_USD:
      min: 10000
      max: 10000000
    OSMO_USDC:
      min: 100000
      max: 100000000
    SEI_USD:
      min: 100000
      max: 100000000
    OSMO_USD:
      min: 100000
      max: 100000000
    ETH_BTC:
      min: 1000
      max: 1000000
    ETH_USD:
      min: 1000
      max: 1000000
    axlETH_USD:
      min: 1000
      max: 1000000
    BTC_USD:
      min: 100
      max: 10000
  min-util-delta: -0.05
  max-util-delta: 0.02
  target-util-delta: -0.02
utilization:
  min-util-delta: -0.1
  max-util-delta: -0.05
trader:
  max-util-delta: 0.05
  min-borrow-fee: 0.1
  max-borrow-fee: 0.2
# Initial prices used for manually set markets
initial-prices:
  ATOM_USD:
    price: 7
    price_usd: 1
  stATOM_USD:
    price: 8
    price_usd: 1
  ETH_BTC:
    price: 0.5
    price_usd: 28000
  OSMO_USDC:
    price: 0.3
    price_usd: 1
  BTC_USD:
    price: 28000
    price_usd: 28000
deployments:
  beta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 3
    default-market-ids:
      - ATOM_USD
      - BTC_USD
  dev:
    wallet-manager-address: osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 3
    default-market-ids:
      - ATOM_USD
      - BTC_USD
  ci:
    wallet-manager-address: osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 3
    default-market-ids:
      - stATOM_USD
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
      - BTC_USD
  debug:
    # Seed phrase: soldier speak spawn sword vivid robot brand stage promote pride grant bench degree bulk armor now sketch extend wheel echo figure net wedding unveil
    wallet-manager-address: levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9
    dev-settings: true
    price: true
    crank: true
    liquidity: false
    utilization: false
    balance: false
    traders: 0
    default-market-ids:
      #- ATOM_USD
      #- OSMO_USD
      #- ETH_BTC
      - BTC_USD
      - ETH_USD
  qa:
    wallet-manager-address: levana1ep4uavfsyw5dp7ymtkpvj8qm4mc8ellph9408d
    dev-settings: true
    price: false
    crank: true
    ignore-stale: true
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
      - BTC_USD
    qa-price-updates: true
overrides:
  seibeta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price: true
    ultra-crank: 2
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 0
    default-market-ids:
      - ETH_USD
      - BTC_USD

    # Gas is expensive on Sei
    min-gas: 1000
    min-gas-in-faucet: 2000000
    min-gas-in-gas-wallet: 1000000
    watcher:
      # Nodes seem to crash often, let's see if this helps
      retries: 10
  seidev:
    wallet-manager-address: osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 3
    default-market-ids:
      - ATOM_USD
      - BTC_USD
    # Gas is expensive on Sei
    min-gas: 1000
    min-gas-in-faucet: 2000000
    min-gas-in-gas-wallet: 1000000
  seidebug:
    wallet-manager-address: levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9
    dev-settings: true
    price: true
    crank: true
    liquidity: false
    utilization: false
    balance: false
    traders: 0
    default-market-ids:
      - BTC_USD
      - ETH_USD
    # Gas is expensive on Sei
    min-gas: 1000
    min-gas-in-faucet: 2000000
    min-gas-in-gas-wallet: 1000000
  injbeta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price: true
    ultra-crank: 0
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 1
    default-market-ids:
      - ETH_USD