price-api: "https://price-api.levana.exchange/"
liquidity:
  markets:
    ATOM_USD:
      min: 10000
      max: 10000000
    OSMO_USDC:
      min: 100000
      max: 100000000
    ETH_BTC:
      min: 1000
      max: 1000000
    ETH_USD:
      min: 1000
      max: 1000000
  min-util-delta: -0.05
  max-util-delta: 0.02
  target-util-delta: -0.02
utilization:
  min-util-delta: -0.1
  max-util-delta: -0.05
trader:
  max-util-delta: 0.05
  min-borrow-fee: 0.1
  max-borrow-fee: 0.2
deployments:
  beta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price-address: osmo1dfagdh540vrqqnuet5rqvdg3uldhhgdxpttmzl
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
  dev:
    wallet-manager-address: osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel
    price-address: osmo1q47uh5e2v8gfr3efy03xs9m0qrz3d2g2fpdc7l
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
  trade:
    wallet-manager-address: osmo19a93ag7hf49zqemds0x8nutldv7288drj6fw74
    price-address: osmo1uvllz6r8aye35rm38jdcjwe7r73wgcxvtsu4c6
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
    trading-competition: true
  ci:
    wallet-manager-address: osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv
    price-address: osmo1pcma8fhzddx6j0uylpcll4ut673t3qqulpu56l
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
  debug:
    # Seed phrase: soldier speak spawn sword vivid robot brand stage promote pride grant bench degree bulk armor now sketch extend wheel echo figure net wedding unveil
    wallet-manager-address: levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9
    # Seed phrase: letter head erode memory sentence ugly loan burden gorilla idea wait boat tattoo owner agent style next lion exclude point lawn wine unknown faculty
    price-address: levana1542ed06vh5e4f9dz5maa4nsj7x2ann6wy5vykr
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
  qa:
    wallet-manager-address: levana1ep4uavfsyw5dp7ymtkpvj8qm4mc8ellph9408d
    price-address: osmo1ssnwszx2dutvlrpwwgefpfyswgrrm059d5mcfe
    dev-settings: true
    price: false
    crank: true
    ignore-stale: true
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
overrides:
  seibeta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price-address: osmo1dfagdh540vrqqnuet5rqvdg3uldhhgdxpttmzl
    price: true
    ultra-crank: 20
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 0
    default-market-ids:
      - ETH_USD
    # Lower gas requirements, we don't have much available on Sei
    min-gas: 1000000
    min-gas-in-faucet: 2000000000
    min-gas-in-gas-wallet: 1000000000
    watcher:
      # Nodes seem to crash often, let's see if this helps
      retries: 10
  seitrade:
    wallet-manager-address: osmo19a93ag7hf49zqemds0x8nutldv7288drj6fw74
    price-address: osmo1uvllz6r8aye35rm38jdcjwe7r73wgcxvtsu4c6
    dev-settings: false
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 0
    default-market-ids:
      - ETH_USD
    trading-competition: true
    # Lower gas requirements, we don't have much available on Sei
    min-gas: 1000000
    min-gas-in-faucet: 2000000000
    min-gas-in-gas-wallet: 3000000000
    watcher:
      # Nodes seem to crash often, let's see if this helps
      retries: 10
  dragonbeta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price-address: osmo1dfagdh540vrqqnuet5rqvdg3uldhhgdxpttmzl
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
    # Can be removed once Dragonfire supports the Pyth oracle
    max-price-age-secs: 1
