sei-testnet:
  pyth:
    contract: sei1kpntez76v38yuxhhaaahdmvjxnr5tkr8tq077smefs7uw70rj5yqw2aewy
    type: edge
  tracker: sei14k4xcy6dfdyqvpvx6njxptry2urcp98f74lv49m36u7gkdkv7s6qleq4tp
  faucet: sei1czf3age49j99yrkxynmetysh3p2x8tp429mv23jme7zj8hytwhesnqngza
  explorer: "https://www.seiscan.app/atlantic-2/txs/"
  rpc-nodes:
  # - https://sei.kingnodes.com/
  - https://test-sei.kingnodes.com
  # - https://test-sei-grpc.kingnodes.com
  #- https://rpc-sei-testnet.rhinostake.com/
  #- https://rpc.atlantic-2.seinetwork.io/
  #- https://sei-testnet-rpc.polkachu.com/
  #- https://sei-a2-rpc.brocha.in/
sei-mainnet:
  pyth:
    contract: sei15d2tyq2jzxmpg32y3am3w62dts32qgzmds9qnr6c87r0gwwr7ynqal0x38
    type: stable
  rpc-nodes:
    - https://sei-priv.kingnodes.com
osmosis-mainnet:
  pyth:
    contract: osmo13ge29x4e2s63a8ytz2px8gurtyznmue4a69n5275692v3qn3ks8q7cwck7
    type: stable
  explorer: "https://www.mintscan.io/osmosis/txs/"
  gas-multiplier: 1.5
osmosis-testnet:
  pyth:
    contract: osmo1lltupx02sj99suakmuk4sr4ppqf34ajedaxut3ukjwkv6469erwqtpg9t3
    type: edge
  tracker: osmo1l3ypxctzcdev9dmyydlzrflqz52f0wsqmzkuyq9dvpdnqx69wvvq9zszh2
  faucet: osmo1ycrm74p7uc976hu2z428l27vxj8l44zu0x0yqjr8gh775qr6gtnq9f3zsz
  explorer: "https://testnet.mintscan.io/osmosis-testnet/txs/"
  rpc-nodes:
  - https://rpc.osmotest5.osmosis.zone
  gas-multiplier: 1.5
juno-testnet:
  tracker: juno1u23qyg0j4y5mzhessf0kcnjuqwg48kpufj5vujsq7kxxgxfnv5pqjmkmr4
  faucet: juno15rwad8twfrj34q7ep2sgrz3lqqs7vj939z9p4kccvfu9qm6mn55qxn7gy3
  explorer: "https://testnet.mintscan.io/juno-testnet/txs/"
stargaze-testnet:
  tracker: stars1vfa0a8846ay2l2ehmqtwxgpcxzes9m598kw6mjh50zgnqhxgwmys7fkew3 
  faucet: stars1pnlmx33qgx7822t7tc73znu0ddkxzcg29rshpls6acdlrrr7snkst4xwq6
  explorer: "https://testnet-explorer.publicawesome.dev/stargaze/tx/"
osmosis-local: {}
