chains:
  dragonfire:
    tracker: levana18cszlvm6pze0x9sz32qnjq4vtd45xehqs8dq7cwy8yhq35wfnn3q6s5ylj
    faucet: levana1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7ff6rr
    explorer: "https://bigdipper.dragonfire.sandbox.levana.finance/transactions/"
    watcher:
      retries: 4
      delay-between-retries: 20
      balance:
        delay: !constant 20
        out-of-date: 180
      gas-check:
        delay: !constant 60
        out-of-date: 180
      liquidity:
        delay: !constant 120
        out-of-date: 60
      trader:
        delay: !random
          low: 120
          high: 1200
        out-of-date: 60
      utilization:
        delay: !constant 120
        out-of-date: 120
      track-balance:
        delay: !constant 60
        out-of-date: 60
      crank:
        delay: !constant 30
        out-of-date: 60
      get-factory:
        delay: !constant 60
        out-of-date: 180
      price:
        delay: !constant 60
        out-of-date: 180
  osmosis-testnet:
    tracker: osmo1l3ypxctzcdev9dmyydlzrflqz52f0wsqmzkuyq9dvpdnqx69wvvq9zszh2
    faucet: osmo1ycrm74p7uc976hu2z428l27vxj8l44zu0x0yqjr8gh775qr6gtnq9f3zsz
    pyth:
     address: osmo12u2vqdecdte84kg6c3d40nwzjsya59hsj048n687m9q3t6wdmqgsq6zrlx 
     endpoint: "https://xc-mainnet.pyth.network"
    explorer: "https://testnet.mintscan.io/osmosis-testnet/txs/"
    watcher:
      retries: 4
      delay-between-retries: 20
      balance:
        delay: !constant 20
        out-of-date: 180
      gas-check:
        delay: !constant 60
        out-of-date: 180
      liquidity:
        delay: !constant 120
        out-of-date: 60
      trader:
        delay: !random
          low: 120
          high: 1200
        out-of-date: 60
      utilization:
        delay: !constant 120
        out-of-date: 120
      track-balance:
        delay: !constant 60
        out-of-date: 60
      crank:
        delay: !constant 30
        out-of-date: 60
      get-factory:
        delay: !constant 60
        out-of-date: 180
      price:
        delay: !constant 60
        out-of-date: 180
  juno-testnet:
    tracker: juno1u23qyg0j4y5mzhessf0kcnjuqwg48kpufj5vujsq7kxxgxfnv5pqjmkmr4
    faucet: juno15rwad8twfrj34q7ep2sgrz3lqqs7vj939z9p4kccvfu9qm6mn55qxn7gy3
    explorer: "https://testnet.mintscan.io/juno-testnet/txs/"
    watcher:
      retries: 4
      delay-between-retries: 20
      balance:
        delay: !constant 20
        out-of-date: 180
      gas-check:
        delay: !constant 60
        out-of-date: 180
      liquidity:
        delay: !constant 120
        out-of-date: 60
      trader:
        delay: !random
          low: 120
          high: 1200
        out-of-date: 60
      utilization:
        delay: !constant 120
        out-of-date: 120
      track-balance:
        delay: !constant 60
        out-of-date: 60
      crank:
        delay: !constant 30
        out-of-date: 60
      get-factory:
        delay: !constant 60
        out-of-date: 180
      price:
        delay: !constant 60
        out-of-date: 180
  stargaze-testnet:
    tracker: stars1vfa0a8846ay2l2ehmqtwxgpcxzes9m598kw6mjh50zgnqhxgwmys7fkew3 
    faucet: stars1pnlmx33qgx7822t7tc73znu0ddkxzcg29rshpls6acdlrrr7snkst4xwq6
    explorer: "https://testnet-explorer.publicawesome.dev/stargaze/tx/"
    watcher:
      retries: 4
      delay-between-retries: 20
      balance:
        delay: !constant 20
        out-of-date: 180
      gas-check:
        delay: !constant 60
        out-of-date: 180
      liquidity:
        delay: !constant 120
        out-of-date: 60
      trader:
        delay: !random
          low: 120
          high: 1200
        out-of-date: 60
      utilization:
        delay: !constant 120
        out-of-date: 120
      track-balance:
        delay: !constant 60
        out-of-date: 60
      crank:
        delay: !constant 30
        out-of-date: 60
      get-factory:
        delay: !constant 60
        out-of-date: 180
      price:
        delay: !constant 60
        out-of-date: 180
price-api: "https://price-api.sandbox.levana.finance/"
pyth-update-age-tolerance: 120
pyth-markets:
  ATOM_USD:
    feeds: [
      { id: "b00b60f88b03a6a625a8d1c048c3f66653edf217439983d037e7222c4e612819", inverted: false }
    ]
  OSMO_USDC:
    feeds: [
      # OSMO/USD
      { id: "5867f5683c757393a0670ef0f701490950fe93fdb006d181c8265a831ac0c5c6", inverted: false },
      # inverted USDC/USD 
      { id: "eaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a", inverted: true }
    ]
    # OSMO_USD (snake_case for compatibility with instantiate message)
    feeds_usd: [
      {id: "5867f5683c757393a0670ef0f701490950fe93fdb006d181c8265a831ac0c5c6", inverted: false }
    ]
  ETH_BTC:
    feeds: [
      # ETH/USD
      {id: "ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace", inverted: false },
      # inverted BTC/USD
      {id: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43", inverted: true }
    ]
    # ETH_USD (snake_case for compatibility with instantiate message)
    feeds_usd: [
      {id: "ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace", inverted: false }
    ]
min-gas: 1000000
min-gas-in-faucet: 10000000000
min-gas-in-gas-wallet: 10000000000
liquidity:
  markets:
    ATOM_USD:
      min: 10000
      max: 10000000
    OSMO_USDC:
      min: 100000
      max: 100000000
    ETH_BTC:
      min: 1000
      max: 1000000
  min-util: 0.85
  max-util: 0.92
  target-util: 0.88
utilization:
  min-util: 0.8
  max-util: 0.85
trader:
  max-util: 0.95
  min-borrow-fee: 0.1
  max-borrow-fee: 0.2
deployments:
  beta:
    wallet-manager-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price-address: osmo1dfagdh540vrqqnuet5rqvdg3uldhhgdxpttmzl
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 100
    default-market-ids:
      - ATOM_USD
  dev:
    wallet-manager-address: osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel
    price-address: osmo1q47uh5e2v8gfr3efy03xs9m0qrz3d2g2fpdc7l
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 30
    default-market-ids:
      - ATOM_USD
  trade:
    wallet-manager-address: osmo19a93ag7hf49zqemds0x8nutldv7288drj6fw74
    price-address: osmo1uvllz6r8aye35rm38jdcjwe7r73wgcxvtsu4c6
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
  ci:
    wallet-manager-address: osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv
    price-address: osmo1pcma8fhzddx6j0uylpcll4ut673t3qqulpu56l
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 50
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
  debug:
    # Seed phrase: soldier speak spawn sword vivid robot brand stage promote pride grant bench degree bulk armor now sketch extend wheel echo figure net wedding unveil
    wallet-manager-address: levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9
    # Seed phrase: letter head erode memory sentence ugly loan burden gorilla idea wait boat tattoo owner agent style next lion exclude point lawn wine unknown faculty
    price-address: levana1542ed06vh5e4f9dz5maa4nsj7x2ann6wy5vykr
    dev-settings: true
    price: true
    crank: true
    liquidity: true
    utilization: true
    balance: true
    traders: 10
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
  qa:
    wallet-manager-address: levana1ep4uavfsyw5dp7ymtkpvj8qm4mc8ellph9408d
    price-address: osmo1ssnwszx2dutvlrpwwgefpfyswgrrm059d5mcfe
    dev-settings: true
    price: false
    crank: true
    default-market-ids:
      - ATOM_USD
      - OSMO_USDC
      - ETH_BTC
