chains:
  dragonfire:
    tracker: levana18cszlvm6pze0x9sz32qnjq4vtd45xehqs8dq7cwy8yhq35wfnn3q6s5ylj
    faucet: levana1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7ff6rr
    explorer: "https://bigdipper.dragonfire.sandbox.levana.finance/transactions/"
  osmosis-testnet:
    tracker: osmo1mmge3fen060uuy7ugwaqq2hn2ue0r8sz656vmk40un4s9daj2r7sjnwtez
    faucet: osmo1dkuqv6u9pjkv2y6vamvd6z5d4k820txsvaes0uglc937aqnny5cqeyva57
    explorer: "https://testnet.mintscan.io/osmosis-testnet/txs/"
price-api: "https://price-api.sandbox.levana.finance/"
min-gas:
  price: 20000000
  crank: 100000000
  nibb: 100000000
  faucet: 10000000000
  faucet-bot: 1000000
  liquidity: 1000000
  utilization: 1000000
  trader: 1000000
deployments:
  beta:
    nibb-address: osmo12vhejqqdgnszlcs7nqdvlx3p5eqyudfslevx3k
    price-address: osmo1dfagdh540vrqqnuet5rqvdg3uldhhgdxpttmzl
    price: true
    crank:
      bot-count: 1
    liquidity: true
    utilization: true
    traders: 100
    nibb:
      markets:
        ATOM_USD:
          target-mid-funding-rates: 0.09
          funding-rates-range: 0.04
          delta-size-threshold: 1000
  dev:
    nibb-address: osmo1lkc7lnq204m4yeydcdg94stkm50jjyglh7ucel
    price-address: osmo1q47uh5e2v8gfr3efy03xs9m0qrz3d2g2fpdc7l
    dev-settings: true
    price: true
    crank:
      bot-count: 1
    liquidity: true
    utilization: true
    traders: 30
    nibb:
      markets:
        ATOM_USD:
          target-mid-funding-rates: 0.09
          funding-rates-range: 0.04
          delta-size-threshold: 1000
  trade:
    nibb-address: osmo19a93ag7hf49zqemds0x8nutldv7288drj6fw74
    price-address: osmo1uvllz6r8aye35rm38jdcjwe7r73wgcxvtsu4c6
    dev-settings: true
    price: true
    crank:
      bot-count: 1
    liquidity: true
    utilization: true
    traders: 10
    nibb:
      markets:
        ATOM_USD:
          target-mid-funding-rates: 0.09
          funding-rates-range: 0.04
          delta-size-threshold: 1000
  ci:
    nibb-address: osmo1ghgpnmxgt6xz463423hhnx8zp99dwt563wnllv
    price-address: osmo1pcma8fhzddx6j0uylpcll4ut673t3qqulpu56l
    dev-settings: true
    price: true
    crank:
      bot-count: 1
    liquidity: true
    utilization: true
    traders: 50
    nibb:
      markets:
        ATOM_USD:
          target-mid-funding-rates: 0.09
          funding-rates-range: 0.04
          delta-size-threshold: 1000
  debug:
    # Seed phrase: soldier speak spawn sword vivid robot brand stage promote pride grant bench degree bulk armor now sketch extend wheel echo figure net wedding unveil
    nibb-address: levana19ta8kepflecc7n2rdruduj9ydt72z2xy0gl5e9
    # Seed phrase: letter head erode memory sentence ugly loan burden gorilla idea wait boat tattoo owner agent style next lion exclude point lawn wine unknown faculty
    price-address: levana1542ed06vh5e4f9dz5maa4nsj7x2ann6wy5vykr
    dev-settings: true
    price: true
    crank:
      bot-count: 1
    liquidity: true
    utilization: true
    traders: 10
    nibb:
      markets:
        ATOM_USD:
          target-mid-funding-rates: 0.09
          funding-rates-range: 0.04
          delta-size-threshold: 1000
  qa:
    nibb-address: levana1ep4uavfsyw5dp7ymtkpvj8qm4mc8ellph9408d
    price-address: osmo1ssnwszx2dutvlrpwwgefpfyswgrrm059d5mcfe
    dev-settings: true
    price: false
    crank:
      bot-count: 1
    nibb: null
