markets:
  ETH_USD:
    config:
      delta_neutrality_fee_sensitivity: 1000000000
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      carry_leverage: 15

    initial-borrow-fee-rate: 0.05

  axlETH_USD:
    config:
      delta_neutrality_fee_sensitivity: 1000000000
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      carry_leverage: 15

    initial-borrow-fee-rate: 0.05

  ATOM_USD:
    config:
      funding_rate_sensitivity: 2
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.1
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.2

  stATOM_USD:
    config:
      funding_rate_sensitivity: 2
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      carry_leverage: 15
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05

  OSMO_USD:
    config:
      trading_fee_notional_size: 0.002
      trading_fee_counter_collateral: 0.002
      max_leverage: 4
      carry_leverage: 2
      funding_rate_sensitivity: 2
      target_utilization: 0.5
      delta_neutrality_fee_sensitivity: 3000000
      borrow_fee_sensitivity: 0.01333333333
      delta_neutrality_fee_cap: 0.03
      delta_neutrality_fee_tax: 0.7
      borrow_fee_rate_min_annualized: 0.06

    initial-borrow-fee-rate: 0.12

  SEI_USD:
    config:
      carry_leverage: 15
      funding_rate_sensitivity: 2
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.01333333333
      delta_neutrality_fee_sensitivity: 15000000
      borrow_fee_rate_min_annualized: 0.04
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.08

  # Currently only used on CI versions of contracts
  OSMO_USDC:
    config:
      trading_fee_notional_size: 0.002
      trading_fee_counter_collateral: 0.002
      max_leverage: 4
      carry_leverage: 2
      delta_neutrality_fee_cap: 0.03
      delta_neutrality_fee_sensitivity: 3000000
      delta_neutrality_fee_tax: 0.7
      liquidity_cooldown_seconds: 3600
    initial-borrow-fee-rate: 0.12
  ETH_BTC:
    config:
      delta_neutrality_fee_sensitivity: 1000000000
      carry_leverage: 15
      liquidity_cooldown_seconds: 3600
    initial-borrow-fee-rate: 0.05
  BTC_USD:
    config:
      delta_neutrality_fee_sensitivity: 5000000000
      borrow_fee_sensitivity: "0.03333333333"
      funding_rate_max_annualized: "0.45"
      borrow_fee_rate_max_annualized: "0.30"
      target_utilization: "0.5"
      funding_rate_sensitivity: 1
      carry_leverage: 15
      borrow_fee_rate_min_annualized: 0.03

    initial-borrow-fee-rate: 0.05

  nBTC_USD:
    config:
      delta_neutrality_fee_sensitivity: 5000000000
      borrow_fee_sensitivity: "0.03333333333"
      funding_rate_max_annualized: "0.45"
      borrow_fee_rate_max_annualized: "0.30"
      target_utilization: "0.5"
      funding_rate_sensitivity: 1
      carry_leverage: 15
      liquidity_cooldown_seconds: 3600

    initial-borrow-fee-rate: 0.05

  AKT_USD:
    config:
      trading_fee_notional_size: 0.002
      trading_fee_counter_collateral: 0.002
      max_leverage: 4
      carry_leverage: 2
      funding_rate_sensitivity: 2
      target_utilization: 0.5
      liquifunding_delay_seconds: 21600
      liquifunding_delay_fuzz_seconds: 3600
      delta_neutrality_fee_cap: 0.03
      delta_neutrality_fee_tax: 0.5
      liquidity_cooldown_seconds: 3600

      # Different from EVMOS
      borrow_fee_rate_min_annualized: 0.06
      borrow_fee_rate_max_annualized: 0.6
      borrow_fee_sensitivity: 0.01333333333
      delta_neutrality_fee_sensitivity: 2500000

    initial-borrow-fee-rate: 0.1

  DOT_USD:
    config:
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.05
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_sensitivity: 90000000
      carry_leverage: 15
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.1

  INJ_USD:
    config:
      funding_rate_sensitivity: 2
      borrow_fee_rate_min_annualized: 0.08
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_sensitivity: 16000000
      delta_neutrality_fee_tax: 0.25
      carry_leverage: 15

    initial-borrow-fee-rate: 0.16
  EUR_USDC:
    config:
      max_leverage: 100
      carry_leverage: 25
      funding_rate_sensitivity: 1
      funding_rate_max_annualized: 0.45
      borrow_fee_rate_min_annualized: 0.03
      borrow_fee_rate_max_annualized: 0.3
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.03333333333
      delta_neutrality_fee_sensitivity: 50000000000
      delta_neutrality_fee_cap: 0.0001

    initial-borrow-fee-rate: 0.05
  GBP_USDC:
    config:
      max_leverage: 100
      carry_leverage: 25
      funding_rate_sensitivity: 1
      funding_rate_max_annualized: 0.45
      borrow_fee_rate_min_annualized: 0.03
      borrow_fee_rate_max_annualized: 0.3
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.03333333333
      delta_neutrality_fee_sensitivity: 50000000000
      delta_neutrality_fee_cap: 0.0001

    initial-borrow-fee-rate: 0.05
  CNH_USDC:
    config:
      trading_fee_notional_size: 0.001
      trading_fee_counter_collateral: 0.001
      max_leverage: 100
      carry_leverage: 25
      funding_rate_sensitivity: 1
      funding_rate_max_annualized: 0.45
      borrow_fee_rate_min_annualized: 0.03
      borrow_fee_rate_max_annualized: 0.3
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.03333333333
      delta_neutrality_fee_sensitivity: 50000000000
      delta_neutrality_fee_cap: 0.0001
      delta_neutrality_fee_tax: 0.05
      liquifunding_delay_seconds: 21600
      liquifunding_delay_fuzz_seconds: 3600
      liquidity_cooldown_seconds: 3600

    initial-borrow-fee-rate: 0.05
  GOLD_USDC:
    config:
      trading_fee_notional_size: 0.001
      trading_fee_counter_collateral: 0.001
      max_leverage: 100
      carry_leverage: 25
      funding_rate_sensitivity: 1
      funding_rate_max_annualized: 0.45
      borrow_fee_rate_min_annualized: 0.03
      borrow_fee_rate_max_annualized: 0.3
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.03333333333
      delta_neutrality_fee_sensitivity: 50000000000
      delta_neutrality_fee_cap: 0.0001
      delta_neutrality_fee_tax: 0.05
      liquifunding_delay_seconds: 21600
      liquifunding_delay_fuzz_seconds: 3600
      liquidity_cooldown_seconds: 3600

    initial-borrow-fee-rate: 0.05

  BNB_USDC:
    config:
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_sensitivity: 150000000
      carry_leverage: 15
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05
  BNB_USDT:
    config:
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_sensitivity: 150000000
      carry_leverage: 15
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05

  SOL_USDC:
    config:
      delta_neutrality_fee_sensitivity: 250000000
      funding_rate_sensitivity: 1.5
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05
  SOL_USDT:
    config:
      delta_neutrality_fee_sensitivity: 250000000
      funding_rate_sensitivity: 1.5
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05

  DOGE_USDC:
    config:
      delta_neutrality_fee_sensitivity: 150000000
      funding_rate_sensitivity: 1.5
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.25

      initial-borrow-fee-rate: 0.05

  LUNA_USDC:
    config:
      delta_neutrality_fee_sensitivity: 3500000
      max_leverage: 4
      carry_leverage: 2
      funding_rate_sensitivity: 2
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.5

      initial-borrow-fee-rate: 0.05

  LINK_USDC:
    config:
      delta_neutrality_fee_sensitivity: 125000000
      funding_rate_sensitivity: 1.5
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_cap: 0.005
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05
  LINK_USDT:
    config:
      delta_neutrality_fee_sensitivity: 125000000
      funding_rate_sensitivity: 1.5
      carry_leverage: 15
      borrow_fee_sensitivity: 0.083333333
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      delta_neutrality_fee_tax: 0.25

    initial-borrow-fee-rate: 0.05

  AXL_USD:
    config:
      max_leverage: 4
      carry_leverage: 2
      funding_rate_sensitivity: 2
      target_utilization: 0.5
      delta_neutrality_fee_sensitivity: 2500000
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_cap: 0.03
      delta_neutrality_fee_tax: 0.5
      borrow_fee_rate_min_annualized: 0.09

    initial-borrow-fee-rate: 0.17

  ryETH_USD:
    config:
      delta_neutrality_fee_sensitivity: 1000000000
      funding_rate_sensitivity: 1.5
      borrow_fee_rate_min_annualized: 0.03
      target_utilization: 0.5
      carry_leverage: 15

    initial-borrow-fee-rate: 0.05


  BTC_INJ: # FIXME need real parameters
    config:
      funding_rate_sensitivity: 2
      borrow_fee_rate_min_annualized: 0.08
      target_utilization: 0.5
      borrow_fee_sensitivity: 0.083333333
      delta_neutrality_fee_sensitivity: 16000000
      delta_neutrality_fee_tax: 0.25
      carry_leverage: 15

    initial-borrow-fee-rate: 0.16
