markets:
  ETH_USD:
    delta_neutrality_fee_sensitivity: 1000000000
    funding_rate_sensitivity: 1.5
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    carry_leverage: 15

  axlETH_USD:
    delta_neutrality_fee_sensitivity: 1000000000
    funding_rate_sensitivity: 1.5
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    carry_leverage: 15

  ATOM_USD:
    delta_neutrality_fee_sensitivity: 50000000
    funding_rate_sensitivity: 2
    carry_leverage: 15
    borrow_fee_sensitivity: 0.083333333
    borrow_fee_rate_min_annualized: 0.1
    target_utilization: 0.5
    delta_neutrality_fee_tax: 0.25

  stATOM_USD:
    funding_rate_sensitivity: 2
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_sensitivity: 50000000
    carry_leverage: 15
    delta_neutrality_fee_tax: 0.25

    # initial borrow fee: 0.05

  OSMO_USD:
    trading_fee_notional_size: 0.002
    trading_fee_counter_collateral: 0.002
    max_leverage: 4
    carry_leverage: 2
    funding_rate_sensitivity: 2
    target_utilization: 0.5
    delta_neutrality_fee_sensitivity: 3000000
    borrow_fee_sensitivity: 0.01333333333
    delta_neutrality_fee_cap: 0.03
    delta_neutrality_fee_tax: 0.7
    borrow_fee_rate_min_annualized: 0.06

  SEI_USD:
    carry_leverage: 15
    funding_rate_sensitivity: 2
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.01333333333
    delta_neutrality_fee_sensitivity: 15000000
    borrow_fee_rate_min_annualized: 0.04
    delta_neutrality_fee_tax: 0.25
    # Set initial borrow fee to 8%

  # Currently only used on CI versions of contracts
  OSMO_USDC:
    trading_fee_notional_size: 0.002
    trading_fee_counter_collateral: 0.002
    max_leverage: 4
    carry_leverage: 2
    delta_neutrality_fee_cap: 0.03
    delta_neutrality_fee_sensitivity: 3000000
    delta_neutrality_fee_tax: 0.7
    liquidity_cooldown_seconds: 3600
  ETH_BTC:
    delta_neutrality_fee_sensitivity: 1000000000
    carry_leverage: 15
    liquidity_cooldown_seconds: 3600
  BTC_USD:
    delta_neutrality_fee_sensitivity: 5000000000
    borrow_fee_sensitivity: "0.03333333333"
    funding_rate_max_annualized: "0.45"
    borrow_fee_rate_max_annualized: "0.30"
    target_utilization: "0.5"
    funding_rate_sensitivity: 1
    carry_leverage: 15
    borrow_fee_rate_min_annualized: 0.03

  nBTC_USD:
    delta_neutrality_fee_sensitivity: 5000000000
    borrow_fee_sensitivity: "0.03333333333"
    funding_rate_max_annualized: "0.45"
    borrow_fee_rate_max_annualized: "0.30"
    target_utilization: "0.5"
    funding_rate_sensitivity: 1
    carry_leverage: 15
    liquidity_cooldown_seconds: 3600

  AKT_USD:
    trading_fee_notional_size: 0.002
    trading_fee_counter_collateral: 0.002
    max_leverage: 4
    carry_leverage: 2
    funding_rate_sensitivity: 2
    target_utilization: 0.5
    liquifunding_delay_seconds: 21600
    liquifunding_delay_fuzz_seconds: 3600
    delta_neutrality_fee_cap: 0.03
    delta_neutrality_fee_tax: 0.5
    liquidity_cooldown_seconds: 3600

    # Different from EVMOS
    borrow_fee_rate_min_annualized: 0.06
    borrow_fee_rate_max_annualized: 0.6
    borrow_fee_sensitivity: 0.01333333333
    delta_neutrality_fee_sensitivity: 2500000

    # Starting borrow fee: 0.1

  DOT_USD:
    funding_rate_sensitivity: 1.5
    borrow_fee_rate_min_annualized: 0.05
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_sensitivity: 90000000
    carry_leverage: 15
    delta_neutrality_fee_tax: 0.25

    # Starting borrow fee: 0.1

  INJ_USD:
    funding_rate_sensitivity: 2
    borrow_fee_rate_min_annualized: 0.08
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_sensitivity: 16000000
    delta_neutrality_fee_tax: 0.25
    carry_leverage: 15

    # Starting borrow fee: 0.16

  EUR_USDC:
    max_leverage: 100
    carry_leverage: 25
    funding_rate_sensitivity: 1
    funding_rate_max_annualized: 0.45
    borrow_fee_rate_min_annualized: 0.03
    borrow_fee_rate_max_annualized: 0.3
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.03333333333
    delta_neutrality_fee_sensitivity: 50000000000
    delta_neutrality_fee_cap: 0.0001

    # Starting borrow fee: 0.05

  GBP_USDC:
    max_leverage: 100
    carry_leverage: 25
    funding_rate_sensitivity: 1
    funding_rate_max_annualized: 0.45
    borrow_fee_rate_min_annualized: 0.03
    borrow_fee_rate_max_annualized: 0.3
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.03333333333
    delta_neutrality_fee_sensitivity: 50000000000
    delta_neutrality_fee_cap: 0.0001

    # Starting borrow fee: 0.05

  CNH_USDC:
    trading_fee_notional_size: 0.001
    trading_fee_counter_collateral: 0.001
    max_leverage: 100
    carry_leverage: 25
    funding_rate_sensitivity: 1
    funding_rate_max_annualized: 0.45
    borrow_fee_rate_min_annualized: 0.03
    borrow_fee_rate_max_annualized: 0.3
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.03333333333
    delta_neutrality_fee_sensitivity: 50000000000
    delta_neutrality_fee_cap: 0.0001
    delta_neutrality_fee_tax: 0.05
    liquifunding_delay_seconds: 21600
    liquifunding_delay_fuzz_seconds: 3600
    liquidity_cooldown_seconds: 3600

    # Starting borrow fee: 0.05
  GOLD_USDC:
    trading_fee_notional_size: 0.001
    trading_fee_counter_collateral: 0.001
    max_leverage: 100
    carry_leverage: 25
    funding_rate_sensitivity: 1
    funding_rate_max_annualized: 0.45
    borrow_fee_rate_min_annualized: 0.03
    borrow_fee_rate_max_annualized: 0.3
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.03333333333
    delta_neutrality_fee_sensitivity: 50000000000
    delta_neutrality_fee_cap: 0.0001
    delta_neutrality_fee_tax: 0.05
    liquifunding_delay_seconds: 21600
    liquifunding_delay_fuzz_seconds: 3600
    liquidity_cooldown_seconds: 3600

    # Starting borrow fee: 0.05

  BNB_USDC:
    funding_rate_sensitivity: 1.5
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_sensitivity: 150000000
    carry_leverage: 15
    delta_neutrality_fee_tax: 0.25
  BNB_USDT:
    funding_rate_sensitivity: 1.5
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_sensitivity: 150000000
    carry_leverage: 15
    delta_neutrality_fee_tax: 0.25

    # Starting borrow fee: 0.05

  SOL_USDC:
    delta_neutrality_fee_sensitivity: 250000000
    funding_rate_sensitivity: 1.5
    carry_leverage: 15
    borrow_fee_sensitivity: 0.083333333
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    delta_neutrality_fee_tax: 0.25
  SOL_USDT:
    delta_neutrality_fee_sensitivity: 250000000
    funding_rate_sensitivity: 1.5
    carry_leverage: 15
    borrow_fee_sensitivity: 0.083333333
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    delta_neutrality_fee_tax: 0.25

    # Starting borrow fee: 0.05

  LINK_USDC:
    delta_neutrality_fee_sensitivity: 125000000
    funding_rate_sensitivity: 1.5
    carry_leverage: 15
    borrow_fee_sensitivity: 0.083333333
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    delta_neutrality_fee_cap: 0.005
    delta_neutrality_fee_tax: 0.25
  LINK_USDT:
    delta_neutrality_fee_sensitivity: 125000000
    funding_rate_sensitivity: 1.5
    carry_leverage: 15
    borrow_fee_sensitivity: 0.083333333
    borrow_fee_rate_min_annualized: 0.03
    target_utilization: 0.5
    delta_neutrality_fee_tax: 0.25

    # Starting borrow fee: 0.05

  AXL_USD:
    max_leverage: 4
    carry_leverage: 2
    funding_rate_sensitivity: 2
    target_utilization: 0.5
    delta_neutrality_fee_sensitivity: 2500000
    borrow_fee_sensitivity: 0.083333333
    delta_neutrality_fee_cap: 0.03
    delta_neutrality_fee_tax: 0.5
    borrow_fee_rate_min_annualized: 0.09

    # Starting borrow fee: 0.17
