markets:
  ETH_USD:
    delta_neutrality_fee_sensitivity: 1000000000
    funding_rate_sensitivity: 1.5
    # Initial deployment to mainnet probably wants a modified max_liquidity too
    # Not setting here since it shouldn't be used for testnet deploys

  # Internal testing contracts, not yet on mainnet
  ATOM_USD:
    delta_neutrality_fee_sensitivity: 200000000
    funding_rate_sensitivity: 2

  OSMO_USD:
    max_leverage: 10
    carry_leverage: 5
    funding_rate_sensitivity: 2
    target_utilization: 0.5
    borrow_fee_sensitivity: 0.01333333333
    delta_neutrality_fee_cap: 0.015
    delta_neutrality_fee_sensitivity: 50000000
    delta_neutrality_fee_tax: 0.25
    max_liquidity: !usd
      amount: "150000"
    trading_fee_notional_size: 0.001
    trading_fee_counter_collateral: 0.001
    borrow_fee_rate_min_annualized: 0.06

  # Currently only used on CI versions of contracts
  OSMO_USDC:
    max_leverage: 10
    carry_leverage: 9
    delta_neutrality_fee_cap: 0.015
    delta_neutrality_fee_sensitivity: 50000000
    delta_neutrality_fee_tax: 0.25
  ETH_BTC:
    delta_neutrality_fee_sensitivity: 1000000000
  BTC_USD:
    delta_neutrality_fee_sensitivity: 5000000000
    max_liquidity: !usd
      amount: "100000"
    borrow_fee_sensitivity: "0.03333333333"
    funding_rate_max_annualized: "0.45"
    borrow_fee_rate_max_annualized: "0.30"
    target_utilization: "0.5"
    funding_rate_sensitivity: 1
