[package]
name = "levana_perpswap_cosmos_shared"
version = "0.1.0-beta.15"
authors = ["Levana Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw-storage-plus = { version = "1.0.1", default-features = false }
serde = { version = "1.0.151", features = ["rc"] }
cosmwasm-std = { version = "1.2.3", features = ["abort", "ibc3"] }
schemars = { version = "0.8.11", default-features = false }
anyhow = "1.0.67"
cw2 = "1.0.0"
serde-json-wasm = "0.4.1"
cosmwasm-schema = "1.1.9"
arbitrary = { version = "1.2.0", optional = true, default-features = false, features = ["derive"] }
serde_json = { version = "1.0.90", default-features = false }
pyth-sdk-cw = "1.0.0"
thiserror = "1"
chrono = { version = "0.4.25", optional = true, default-features = false, features = ["std"]}


[features]
debug_log = []
arbitrary = ["dep:arbitrary"]

[dev-dependencies]
quickcheck = "1"
