[package]
name = "perps-exes"
description = "Helper executables for testing, deploying, and running bots"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
msg = { path = "../msg", package = "levana_perpswap_cosmos_msg", features = [
	"bridge",
] }
shared = { path = "../shared", package = "levana_perpswap_cosmos_shared", features = [
	"chrono",
] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
log = "0.4.20"
cosmos = { git = "https://github.com/Levana-Protocol/levana-cosmos-rs.git", rev = "a3690574e2ca75b9581838644d3d9b456fbdd453" }
cosmwasm-std = "1.1.9"
tokio = { version = "1.34.0", default-features = false, features = [
	"time",
	"rt",
	"macros",
	"process",
	"tracing",
] }
once_cell = "1"
multi_test = { package = "levana_perpswap_multi_test", path = "../multi_test", default-features = false }
clap = { version = "4.4.10", features = ["derive", "env"] }
fs-err = "2.11.0"
env_logger = "0.10.1"
dotenv = "0.15"
hex = "0.4"
sha2 = "0.10.8"
reqwest = { version = "0.11.22", default-features = false, features = [
	"rustls-tls",
	"json",
	"gzip",
] }
chrono = { version = "0.4.31", features = ["serde"] }
axum = { version = "0.7.1", features = [ "tracing", "macros"] }
axum-extra = { version = "0.9.0", features = ["typed-routing", "typed-header"] }
tower-http = { version = "0.5.0", features = ["cors", "auth", "timeout", "limit", "trace"] }
futures = "0.3.29"
tokio-tungstenite = "0.20.1"
tokio-util = { version = "0.7.10", features = ["full"] }
cw-multi-test = "0.16.2"
rand = "0.8"
pyth-sdk-cw = "1.2.0"
csv = "1.3.0"
tonic = "0.10.2"
askama = "0.12.1"
cw-utils = "1.0.1"
thiserror = "1.0.50"
resvg = "0.36.0"
axum-macros = "0.4.0"
mime = "0.3.17"
sqlx = { version = "0.7.3", features = [
	"runtime-tokio-rustls",
	"postgres",
] }
itertools = "0.12.0"
sentry = { version = "0.32.0", default-features = false, features = [ # Newer sentry require rustc 1.66+
	"reqwest",
	"rustls",
	"tracing",
] }
sentry-tracing = "0.32.0"
async-channel = "2.1.1"
pid1 = "0.1.1"
dashmap = "5.5.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
parking_lot = { version = "0.12.1", features = ["deadlock_detection"] }
bigdecimal = { version = "0.4.2", features = ["serde"]}
http = "1.0.0"
headers = "0.4.0"
tower = "0.4.13"

[features]
default = []
sanity = ["multi_test/sanity"]
