[package]
name = "perps-exes"
description = "Helper executables for testing, deploying, and running bots"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
msg = { path = "../msg", package = "levana_perpswap_cosmos_msg", features = [
       "bridge",
] }
shared = { path = "../shared", package = "levana_perpswap_cosmos_shared", features = [
       "chrono",
] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.2"
log = "0.4.17"
cosmos = { git = "https://github.com/Levana-Protocol/levana-cosmos-rs.git", rev = "1eb85a9c35bf47ba2c772f47e6f88b7d8088fc7f" }
cosmwasm-std = "1.1.9"
tokio = { version = "1.24.1", default-features = false, features = ["time"] }
once_cell = "1"
multi_test = { package = "levana_perpswap_multi_test", path = "../multi_test", default-features = false }
clap = { version = "4.0.29", features = ["derive", "env"] }
fs-err = "2"
env_logger = "0.10.0"
dotenv = "0.15"
hex = "0.4"
sha2 = "0.10"
reqwest = { version = "0.11.11", default-features = false, features = [
       "rustls-tls",
       "json",
       "gzip",
] }
chrono = { version = "0.4.19", features = ["serde"] }
axum = { version = "0.6", features = ["headers"] }
axum-extra = { version = "0.7", features = ["typed-routing"] }
tower-http = { version = "0.3.4", features = ["cors", "auth"] }
futures = "0.3.26"
tokio-tungstenite = "*"
tokio-util = { version = "0.7.7", features = ["full"] }
cw-multi-test = "0.16.2"
rand = "0.8"
pyth-sdk-cw = "1.0.0"
csv = "1.2.2"
tonic = "0.8.3"
askama = "0.12"
cw-utils = "1.0.1"
thiserror = "1"
resvg = "0.34"
axum-macros = "0.3.7"
mime = "0.3.17"
sqlx = { version = "0.6.3", features = [
       "runtime-tokio-rustls",
       "postgres",
       "offline",
] }
itertools = "0.10.5"
sentry = { version = "0.29", default-features = false, features = [ # Newer sentry require rustc 1.66+
       "reqwest",
       "rustls",
] }
async-channel = "1.9"
hyper = "0.14"
pid1 = "0.1.0"

[features]
default = []
sanity = ["multi_test/sanity"]
