[package]
name = "perps-exes"
description = "Helper executables for testing, deploying, and running bots"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
msg = { path = "../msg", package = "levana_perpswap_cosmos_msg", features = ["bridge"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.2"
log = "0.4.17"
cosmos = { git = "https://github.com/Levana-Protocol/levana-cosmos-rs.git", branch = "sei-gas-hack" }
cosmwasm-std = "1.1.9"
tokio = { version = "1.24.1", default-features = false, features = ["time"] }
once_cell = "1"
multi_test = { package = "levana_perpswap_multi_test", path = "../multi_test", default-features = false }
clap = { version = "4.0.29", features = ["derive", "env"] }
fs-err = "2"
env_logger = "0.10.0"
dotenv = "0.15"
hex = "0.4"
sha2 = "0.10"
parking_lot = "0.12.1"
reqwest = { version = "0.11.11", default-features = false, features = [
       "rustls-tls",
       "json",
       "gzip",
] }
chrono = { version = "0.4.19", features = ["serde"] }
rust_decimal = "1.26.1"
axum = "0.6"
tower-http = { version = "0.3.4", features = ["cors", "auth"] }
futures = "0.3.26"
tokio-tungstenite = "*"
tokio-util = {version = "0.7.7", features = ["full"]}
cw-multi-test = "0.16.2"
rand = "0.8"
pyth-sdk-cw = "1.0.0"
csv = "1"
tonic = "0.8.3"
askama = "0.12"
cw-utils = "1.0.1"

[features]
default = []
sanity = ["multi_test/sanity"]
