[package]
name = "levana-fuzz"
version = "0.1.0-beta.4"
authors = ["Levana Team"]
edition = "2021"

[dependencies]
multi_test = {package = "levana_perpswap_multi_test", path = "../multi_test", features = ["arbitrary"] }
perpswap = {package = "levana_perpswap_cosmos", path = "../perpswap", features = ["arbitrary"] }
libfuzzer-sys = "0.4"
cosmwasm-std = { workspace = true, features = ["abort"] }
anyhow = "1.0.93"
arbitrary = { version = "1.4.1", features = ["derive"] }

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "market"
path = "fuzz_targets/market.rs"
test = false
doc = false
