[package]
name = "levana-fuzz"
version = "0.1.0-beta.4"
authors = ["Levana Team"]
edition = "2021"

[dependencies]
multi_test = {package = "levana_perpswap_multi_test", path = "../multi_test", features = ["arbitrary"] }
msg = {package = "levana_perpswap_cosmos_msg", path = "../msg", features = ["arbitrary"] }
libfuzzer-sys = "0.4"
cosmwasm-std = "1.5.4"
anyhow = "1.0.69"
arbitrary = { version = "1.2.0", features = ["derive"] }

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "market"
path = "fuzz_targets/market.rs"
test = false
doc = false
