[package]
name = "cosmwasm-schema-derive"
version = "2.0.0-beta.1"
authors = ["Tomasz Kurcz <tom@confio.gmbh>"]
edition = "2021"
description = "Derive macros for cosmwasm-schema"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "printing", "extra-traits"] }

[lib]
proc-macro = true
