[package]
name = "stress_test_frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.61"
wasm-bindgen-futures= "0.4.34"
gloo-events = "0.1.2"
gloo-timers = { version = "0.2.6", features = ["futures"] }
wasm-logger = { version = "0.2.0", optional = true }
serde-wasm-bindgen = "0.4.5"
serde = "1.0.199"
serde_json = "1.0.93"
anyhow = "1.0.82"
cfg-if = "1.0.0"
log = "0.4.17"
console_error_panic_hook = { version = "0.1.7", optional = true }
futures = "0.3.26"
dominator = "0.5.32"
futures-signals = "0.3.31"
awsm_web = { version = "0.38.0", features = ["loaders", "dom", "serde_iso", "tick", "webgl"], default-features = false }
once_cell = "1.17.1"
dominator_helpers = "0.7.2"
msg = {package = "levana_perpswap_cosmos_msg", path = "../msg", features = ["bridge"]}
cosmwasm-std = { workspace = true, features = ["abort"] }
chrono = "0.4.31"
async-lock = "2.6.0"
rand = "0.8.5"
getrandom = { version = "0.2.8", features = ["js"] }
gloo-net = "0.2.6"
glam = "0.23.0"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "console",
    "MouseEvent",
    "Document",
    "Element",
    "HtmlAnchorElement",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "UrlSearchParams",
    "Node",
    "Window",
    "WebGl2RenderingContext",
    "Navigator",
    "Clipboard",
    "Performance"
]
[features]
default = []
dev = ["wasm-logger", "console_error_panic_hook","awsm_web/unwrap_verbose"]
