[package]
name = "levana_perpswap_multi_test"
version = "0.1.0-beta.15"
authors = ["Levana Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
msg = {package = "levana_perpswap_cosmos_msg", path = "../msg" }
serde = "1.0.151"
serde_json = "1.0.93"
cosmwasm-std = { version = "1.5.4", features = ["abort"] }
anyhow = { version = "1.0.67", features = ["backtrace"] }
cw-multi-test = "0.16.2"
market = {package = "levana_perpswap_cosmos_market", path = "../../contracts/market" }
factory = {package = "levana_perpswap_cosmos_factory", path = "../../contracts/factory" }
position_token = {package = "levana_perpswap_cosmos_position_token", path = "../../contracts/position_token" }
liquidity_token = {package = "levana_perpswap_cosmos_liquidity_token", path = "../../contracts/liquidity_token" }
cw20 = {package = "levana_perpswap_cosmos_cw20", path = "../../contracts/cw20" }
rand = "0.8.5"
once_cell = "1.16.0"
arbitrary = { version = "1.2.0", optional = true, default-features = false, features = ["derive"] }
cosmos-sdk-proto = { version = "0.16.0", features = ["cosmwasm"] }
cw2 = "1.0.0"
proptest = "1.1.0"
dotenv = "0.15.0"
cosmwasm-schema = {git = "https://github.com/Levana-Protocol/cosmwasm.git", rev = "6e36567b8359214f6690c8de081bb1e237803fb1", features=["allow-unknown-fields"] }
cw-storage-plus = { version = "1.2.0", default-features = false }

[features]
default = ["sanity"]
proptest = ["arbitrary"]
arbitrary = ["msg/arbitrary", "dep:arbitrary"]
sanity = ["market/sanity"]
