[package]
name = "levana_perpswap_cosmos_msg"
version = "0.1.0-beta.15"
authors = ["Levana Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.90"
serde = "1.0.151"
cosmwasm-std = { version = "1.2.3", default-features = false, features = [
	"abort",
] }
schemars = "0.8.11"
cw-storage-plus = { version = "1.0.1", default-features = false }
anyhow = "1.0.67"
cw-utils = "1.0.1"
arbitrary = { version = "1.2.0", optional = true, features = ["derive"] }
cosmwasm-schema = "1.1.9"
cw2 = "1.0.0"
enum-iterator = "1.2"
once_cell = "1.17"
shared = { path = "../shared", package = "levana_perpswap_cosmos_shared" }
pyth-sdk-cw = "1.0.0"

[dev-dependencies]
fs_extra = "1.2.0"
quickcheck = "1"

[features]
default = ["bridge"]
arbitrary = ["dep:arbitrary", "shared/arbitrary"]
bridge = []
