name: Bots Docker Image

on:
  workflow_dispatch:
  schedule:
    # For cache, run at 9 AM UTC daily
    - cron: "0 9 * * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  bots-image:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-bots-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.25.2,cross@0.2.5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          workspaces: |
            .
      - name: Dependencies
        run: sudo apt install musl-tools -y
      - name: Build bots binary (ARM64)
        run: just cargo-bots-release-arm
      - name: Build image
        run: just build-bots-image
      - name: Push image
        run: just push-bots-image
        if: ${{ github.event_name != 'schedule' }}
