name: Build LocalOsmosis

on:
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "2.12.2"
      - uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -ex
          # At the moment, contract size exceeds the limitation of CosmWasm (Osmosis does not change that, either). This `size` version increases the number to very large to get the development going. After the problem is fixed, we should revert to standard version.
          git clone --filter=tree:0 -b size https://github.com/fpco/osmosis.git
          cd osmosis
          make localnet-init
          docker tag local:osmosis "ghcr.io/${GITHUB_REPOSITORY,,}/localosmosis:size"
          docker push "ghcr.io/${GITHUB_REPOSITORY,,}/localosmosis:size"
