name: Committer Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get PR Commits
        id: "get-pr-commits"
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          COMMITS: ${{ steps.get-pr-commits.outputs.commits }}
        run: |
          set -eux -o pipefail
          jq -r '.[] | .commit.committer.email' <<< "${COMMITS}" | while read -r e; do
            [ "${e#*@}" == 'levana.exchange' ]
          done
